version: '3.5'

services:
  broker:
    image: kmqtt:latest
    networks:
      - main
    ports:
      - '1883:1883'
      - '8000:8000'
    deploy:
      mode: replicated
      replicas: 2

networks:
  main:
    driver: overlay
